name: Test

on:
  push:
    branches-ignore:
      - main
      - dev
  workflow_dispatch:
  workflow_call:
    inputs:
      STAGE:
        required: false
        type: string
        default: new
      DOMAIN_NAME:
        required: false
        type: string
        default: 'dev.dailyidea.com'
      S3_STATIC_DOMAIN:
        required: false
        type: string
        default: 'dailyidea-serverless-static-new'
      S3_DOMAIN:
        required: false
        type: string
        default: 'dailyidea-serverless-new.s3.amazonaws.com/client'
      API_URL:
        required: false
        type: string
        default: 'https://api-dev.dailyidea.com/api/v1/'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_DSN:
        required: true

env:
  AWS_REGION: us-east-1
  CERTIFICATE_NAME: '*.dailyidea.com'
  SENTRY_PUBLISH_RELEASE: '1'
  GTM_ID: 'G-9S69GW324J'
  SENTRY_ORG: 'dailyidea-ni'
  SENTRY_PROJECT: 'frontend-dev'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ inputs.STAGE }}
      DOMAIN_NAME: ${{ inputs.DOMAIN_NAME }}
      S3_STATIC_DOMAIN: ${{ inputs.S3_STATIC_DOMAIN }}
      S3_DOMAIN: ${{ inputs.S3_DOMAIN }}
      API_URL: ${{ inputs.API_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    if: ${{ false }}  # disable for now
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install # --check-files --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build-ci

  tests:
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ inputs.STAGE }}
      DOMAIN_NAME: ${{ inputs.DOMAIN_NAME }}
      S3_STATIC_DOMAIN: ${{ inputs.S3_STATIC_DOMAIN }}
      S3_DOMAIN: ${{ inputs.S3_DOMAIN }}
      API_URL: ${{ inputs.API_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install # --check-files --frozen-lockfile --non-interactive

      - name: Lint
        run: yarn lint
